//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWWTest.TestingData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Data {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Data() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LWWTest.TestingData.Data", typeof(Data).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://journals.lww.com/.
        /// </summary>
        internal static string baseURL {
            get {
                return ResourceManager.GetString("baseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chrome.
        /// </summary>
        internal static string browser1 {
            get {
                return ResourceManager.GetString("browser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chrome.
        /// </summary>
        internal static string browser2 {
            get {
                return ResourceManager.GetString("browser2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Yahor_Staravoitau\Documents\Visual Studio 2015\Projects\LWWTest\Responsive-Batch-6.xlsx.
        /// </summary>
        internal static string excelPath {
            get {
                return ResourceManager.GetString("excelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early-Life Obesity.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Yahor_Staravoitau\Documents\Visual Studio 2015\Projects\LWWTest\LWWTest\bin\Debug.
        /// </summary>
        internal static string webDriverPath {
            get {
                return ResourceManager.GetString("webDriverPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\Yahor_Staravoitau\Documents\Visual Studio 2015\Projects\LWWTest\LWWTest\TestingData\JournalTestData.xml.
        /// </summary>
        internal static string xmlPath {
            get {
                return ResourceManager.GetString("xmlPath", resourceCulture);
            }
        }
    }
}
